### ISSUE TITLE
Update to Enzyme v0.13

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Reactant.jl#117]
Hi there! I see that this package has no CompatHelper workflow. I'm sure you're aware of it but just to keep track, there's a new Enzyme release and Reactant might need to update its compat bounds, along with a few other internals.

**Comment by gdalle** [comment]
thanks @avik-pal! can we get a release with those changes so that I experiment with them in DI?

**Comment by mofeing** [comment]
@gdalle probably will get a new patch release as soon as #128 and #126 get merged.
