### ISSUE TITLE
Max Pooling doesn't give correct answers for certain padding

### ISSUE THREAD

**Issue by avik-pal** [EnzymeAD/Reactant.jl#122]
See the tests marked broken in https://github.com/EnzymeAD/Reactant.jl/pull/110

**Comment by wsmoses** [comment]
can you post a MWE?

**Comment by avik-pal** [comment]
Actually digging deeper Reactant pads with `-Inf` (which should be the correct thing to do) while NNlib pads with an arbitrary large number.

**Comment by Pangoraw** [comment]
Should we do something like this too ?

https://github.com/FluxML/NNlib.jl/blob/44a6b048cca26af680f0eb173f0c2dd92786b219/src/impl/pooling_direct.jl#L62
