### ISSUE TITLE
Shortcuts for `to_rarray`

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Reactant.jl#138]
In DifferentiationInterface, the most frequent inputs for `Reactant.to_rarray` will be `Number`s and `AbstractArray`s. For these types, we can short-circuit the recursive tracing and gain a lot of performance:

```julia
julia> using Reactant: ConcreteRArray, to_rarray

julia> using BenchmarkTools

julia> to_rarray_fast(x::Number) = x
to_rarray_fast (generic function with 2 methods)

julia> to_rarray_fast(x::AbstractArray) = ConcreteRArray(x)
to_rarray_fast (generic function with 2 methods)

julia> x0, x1 = 1.0, [1.0]
(1.0, [1.0])

julia> @btime to_rarray($x0);
  228.749 ns (9 allocations: 672 bytes)

julia> @btime to_rarray_fast($x0);
  2.271 ns (0 allocations: 0 bytes)

julia> @btime to_rarray($x1);
  1.058 μs (19 allocations: 1.36 KiB)

julia> @btime to_rarray_fast($x1);
  563.778 ns (4 allocations: 144 bytes)
```

Should I open a PR?

**Comment by wsmoses** [comment]
Yeah! Though for the abstractarray one it should only be for an Array of
floats (not say a sliced array or array of array of floats)

**Comment by gdalle** [comment]
Why not for a sliced array?

**Comment by wsmoses** [comment]
I think the concreterarray constructor only takes a dense array.

Also can we avoid a separate name for this and just have a specialization
of the default that doesn’t recur if the top level is a known type?
