### ISSUE TITLE
Can I compile in-place functions?

### ISSUE THREAD

**Issue by gdalle** [EnzymeAD/Reactant.jl#152]
There's no such example in the readme, but will I run into trouble if I try to compile an in-place function `f!(y, x)`?

**Comment by wsmoses** [comment]
Yup!

**Comment by wsmoses** [comment]
Sorry I meant to say “yes that is supported”

**Comment by mofeing** [comment]
@gdalle check out the "buffer donation" tests https://github.com/EnzymeAD/Reactant.jl/blob/main/test/buffer_donation.jl
