### ISSUE TITLE
What is a device to the RArray?

### ISSUE THREAD

**Issue by avik-pal** [EnzymeAD/Reactant.jl#16]
> alternatively construct RArrays with a device

I don't see a device argument to ConcreteRArray. Is this currently not implemented?

Also, can we directly pass a Ptr to the data for ConcreteRArray, for example, if we have a CuArray input to a Lux model, I want to wrap it as a ConcreteRArray without paying the cost to copy it.

**Comment by avik-pal** [comment]
I see that there is a `client` kwarg. Maybe we can support constructing it via KernelAbstractions backend?

But more importantly, we should document how to pass in the client

**Comment by wsmoses** [comment]
> > alternatively construct RArrays with a device
> 
> I don't see a device argument to ConcreteRArray. Is this currently not implemented?
> 
> Also, can we directly pass a Ptr to the data for ConcreteRArray, for example, if we have a CuArray input to a Lux model, I want to wrap it as a ConcreteRArray without paying the cost to copy it.

Reactant/XLA needs to fully own its memory so the latter won’t be possible (or at least easy)

**Comment by avik-pal** [comment]
With https://lux.csail.mit.edu/stable/api/Accelerator_Support/MLDataDevices#MLDataDevices.reactant_device the original intent of the question has now been resolved
