### ISSUE TITLE
Abstract interpretation over `ReactantInterpreter` sometimes skips overriden methods

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#189]
There are times when interpreting over a `ReactantInterpreter` doesn't correctly replace the overriden methods in `ReactantMethodTable`. For example, https://github.com/EnzymeAD/Reactant.jl/issues/183#issuecomment-2425206624.

After doing a lil research, it seems that this behavior is due to inlining: apparently inlined functions cannot be "interpreted" (@vchuravy correct me if I'm wrong).

Solution is to add a method for `Core.Compiler.inlining_policy` on `ReactantInterpreter` that forbids inlining of the overriden methods.

Some useful links:
- https://github.com/compintell/Mooncake.jl/blob/faa63971859a4758034a1e77e47014b8a0e95130/src/interpreter/abstract_interpretation.jl#L158-L203
- https://github.com/EnzymeAD/Enzyme.jl/blob/9e945a5936f75eaab891361948148342c8f8772d/src/compiler/interpreter.jl#L250-L268
- https://github.com/JuliaLang/julia/blob/1fd7ada972911c181750d104604487a35ae3bea9/test/compiler/AbstractInterpreter.jl#L414-L433

**Comment by wsmoses** [comment]
Oh yeah fair enough we should probably mark these as noinline here .

Cc @gbaraldi @aviatesk

**Comment by vchuravy** [comment]
> After doing a lil research, it seems that this behavior is due to inlining: apparently inlined functions cannot be "interpreted"

Yeah that sounds wrong to me. How are you all executing the code?

**Comment by mofeing** [comment]
> Yeah that sounds wrong to me. How are you all executing the code?

Just `Base.code_ircode` with our interpreter, wrap it into an `OpaqueClosure` and run.

https://github.com/EnzymeAD/Reactant.jl/blob/ad508b99b4f4fed18d368885d457bcb7ad8f6d08/src/utils.jl#L90-L101

The overlayed method for `Enzyme.autodiff` is in here (`@reactant_override` is just an alias for `@overlay ReactantMethodTable`): https://github.com/EnzymeAD/Reactant.jl/blob/ad508b99b4f4fed18d368885d457bcb7ad8f6d08/src/Interpreter.jl#L245-L247

**Comment by aviatesk** [comment]
FWIW, this is how `EnzymeInterpreter` deals with this sort of stuff: https://github.com/EnzymeAD/Enzyme.jl/blob/72763e9aa28978ac820c286c01d4bfd00aa451a3/src/compiler/interpreter.jl#L112-L269

**Comment by vchuravy** [comment]
> with our interpreter, wrap it into an OpaqueClosure and run.

... 

and you are sure that you don't hit a dynamic dispatch somewhere? Or that the overlay didn't apply due to a type-instability/mis-match?

Can you do a MWE?

**Comment by mofeing** [comment]
Note that `Enzyme.autodiff(Forward, ...)` does use the overlayed method, although fails due to other things https://github.com/EnzymeAD/Reactant.jl/issues/183#issuecomment-2426420949.

**Comment by mofeing** [comment]
@wsmoses is `Enzyme.gradient` doing dynamic dispatch on `ForwardMode`?
