### ISSUE TITLE
Resource exhaustion when compiling many functions

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#190]
Some of my algorithms change its structure on every iteration, so I need to recompile the function on each iteration. This is sth that works well on Jax. Aside of the huge performance overhead we're now having in Reactant (which may need some refactoring on `Thunk` and `compile` to zero the amount of compilation from the Julia side to improve it), I'm getting the following error after running many compilations.

Some notes:
- It always fails on the same number of iterations, suggesting that each `compile` takes some resource that's it's not releasing and the resource size is constant.
- This resource size might be machine-dependent. I've just tried on macOS aarch64.

![Image](https://github.com/user-attachments/assets/9ea8abf0-75ff-4461-90df-6b53b8613114)

# MWE

```julia
julia> x = rand(2,2)
julia> y = Reactant.to_rarray(x)

julia> for _ in 1:10_000
           f = @compile sum(y)
       end
LLVM ERROR: pthread_create failed: Resource temporarily unavailable

[27943] signal (6): Abort trap: 6
in expression starting at REPL[18]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 175047067 (Pool: 174829757; Big: 217310); GC: 115
fish: Job 1, 'julia +1.10' terminated by signal SIGABRT (Abort)
```

**Comment by wsmoses** [comment]
can you trace in rr or soemthing with a debug jll to ascertain what resource is failing to be allocated?

**Comment by wsmoses** [comment]
I never fully got things setup iirc, but also in principle [SetLogLevel](https://github.com/EnzymeAD/Reactant.jl/blob/ad508b99b4f4fed18d368885d457bcb7ad8f6d08/deps/ReactantExtra/API.cpp#L84C17-L84C28) might force a lot of debug to spew which may be helpful

**Comment by mofeing** [comment]
Related https://github.com/jax-ml/jax/issues/16272

**Comment by wsmoses** [comment]
Yeah we should also disable threading in our mlir contexts too -- I thought we fixed this earlier on the constructor for mlicontext, but maybe only just discussed it
