### ISSUE TITLE
Error on regenerating "libMLIR_h.jl" on GitHub runner

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#201]
The "Regenerate MLIR bindings" is currently failing when regenerating the "libMLIR_h.jl" file. Logs show that it fails on downloading the `GCCBootstrap` artifacts because it fails on creating a temporary directory in `~/.julia/artifacts/` due to the path being read-only.

https://github.com/EnzymeAD/Reactant.jl/actions/runs/11541259802/job/32123044918

```
 Downloading artifact: GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked
     Failure artifact: GCCBootstrap-x86_64-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked
ERROR: LoadError: IOError: mktempdir("/home/runner/.julia/artifacts"): read-only file system (EROFS)
```

CC @Pangoraw

**Comment by Pangoraw** [comment]
Needs precompile with the instantiate ?

**Comment by mofeing** [comment]
> Needs precompile with the instantiate ?

Shouldn't matter? It will fail with the same problem.

**Comment by Pangoraw** [comment]
yeah those are lazy artifacts which need to be prefetched

**Comment by mofeing** [comment]
Not fixed yet. Now the error is

```
ERROR: LoadError: ArgumentError: Package BinaryBuilderBase [7f725544-6523-48cd-82d1-3fa08ff4056e] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```

**Comment by Pangoraw** [comment]
it seems to be fixed! https://github.com/EnzymeAD/Reactant.jl/actions/runs/11550355978/job/32145171958
