### ISSUE TITLE
Track closures' captured variables

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#32]
From Julia documentation,
> A closure is simply a callable object with field names corresponding to captured variables. For example, the following code:
> ```julia
> function adder(x)
>     return y->x+y
> end
> ```
> is lowered to (roughly):
> ```julia
> struct ##1{T}
>     x::T
> end
> 
> (_::##1)(y) = _.x + y
> 
> function adder(x)
>     return ##1(x)
> end
> ```

It shouldn't be hard to add support for closures. We just need to correctly track the captured variables in `Reactant.make_mlir_fn`, right?

**Comment by wsmoses** [comment]
So we already handle it in make mlir fn, we just need to update the code
which uses make mlir fn
