### ISSUE TITLE
Handling Wrapped Arrays Correctly

### ISSUE THREAD

**Issue by avik-pal** [EnzymeAD/Reactant.jl#345]
- [x] SubArray
- [x] Adjoint
- [x] Transpose
- [x] Diagonal
- [x] WrappedReshapedArray
- [x] PermutedDimsArray
- [x] LowerTriangular
- [x] UnitLowerTriangular
- [x] UpperTriangular
- [x] UnitUpperTriangular
- [x] Tridiagonal
- [x] Symmetric
- [ ] ~WrappedReinterpretArray~

For each of this we need 2 functions:

- `materialize_traced_array` - This unwraps all wrappers and generates a `TracedRArray`
- `set_mlir_data!` - Set the `mlir_data` field for the ancestor

**Comment by mofeing** [comment]
isn't this `materialize_traced_array` the same as calling `collect` on the wrapped arrays? maybe we could overload `Base.collect` for that

**Comment by avik-pal** [comment]
`collect` always returns an `Array` for dense types as well

```julia
julia> collect(JLArray(rand(3)))
3-element Vector{Float64}:
 0.6608065357704661
 0.47618948352793733
 0.6460190608019499
```
