### ISSUE TITLE
Set up GPU CI

### ISSUE THREAD

**Issue by wsmoses** [EnzymeAD/Reactant.jl#41]

**Comment by wsmoses** [comment]
@avik-pal would you mind taking a look at this (clearly I don't know how to set things up properly)

**Comment by avik-pal** [comment]
I can't see the settings page on buildkite, can you give me access there? If you can't find my name, adding `LuxDL` or `SciML` team would also do

**Comment by wsmoses** [comment]
I added LuxDL, 

<img width="929" alt="Screenshot 2024-08-21 at 10 13 16 PM" src="https://github.com/user-attachments/assets/fed8ac57-08fc-4a1b-a9c1-ad08faa21d28">

**Comment by avik-pal** [comment]
can see it, thanks!
