### ISSUE TITLE
Print "donated" attribute on `@code_hlo`

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#97]
Currently, `@code_hlo` doesn't print information of whether a buffer is being donated.

That info would be useful for testing buffer donation.

**Comment by wsmoses** [comment]
@mofeing any updates here btw?

**Comment by mofeing** [comment]
Nope sorry, I'm quite busy until mid October 😓

**Comment by mofeing** [comment]
Donated args are not printed in `@code_hlo`, but they are tested in #126
